### ISSUE TITLE
Internal error: confirm_token was not found in Google drive link

### ISSUE THREAD

**Issue by yananchen1989** [pytorch/text#1678] opened 2022-04-09 17:31 UTC
torchtext version: 0.11.2
when I try download dataset it comes out the error below

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-3-d8c0a1adeb8a> in <module>
>       3     if dsn != 'yahoo':
>       4         continue
> ----> 5     ds_train, ds_test =  f(root=path, split=('train', 'test'))
>       6     df_train, df_test = pd.DataFrame(ds_train, columns=['label', 'content']), pd.DataFrame(ds_test, columns=['label','content'])
>       7     print(dsn, df_train.shape[0], df_test.shape[0])
> 
> ~/.conda/envs/env/lib/python3.8/site-packages/torchtext/data/datasets_utils.py in wrapper(root, *args, **kwargs)
>     255             if not os.path.exists(new_root):
>     256                 os.makedirs(new_root)
> --> 257             return func(root=new_root, *args, **kwargs)
>     258
>     259         return wrapper
> 
> ~/.conda/envs/env/lib/python3.8/site-packages/torchtext/data/datasets_utils.py in new_fn(root, split, **kwargs)
>     217         result = []
>     218         for item in _check_default_set(split, splits, fn.__name__):
> --> 219             result.append(fn(root, item, **kwargs))
>     220         return _wrap_datasets(tuple(result), split)
>     221
> 
> ~/.conda/envs/env/lib/python3.8/site-packages/torchtext/datasets/yahooanswers.py in YahooAnswers(root, split)
>      26 @_wrap_split_argument(('train', 'test'))
>      27 def YahooAnswers(root, split):
> ---> 28     dataset_tar = download_from_url(URL, root=root,
>      29                                     path=os.path.join(root, _PATH),
>      30                                     hash_value=MD5, hash_type='md5')
> 
> ~/.conda/envs/env/lib/python3.8/site-packages/torchtext/utils.py in download_from_url(url, path, root, overwrite, hash_value, hash_type)
>     114
>     115     # download data and move to path
> --> 116     _DATASET_DOWNLOAD_MANAGER.get_local_path(url, destination=path)
>     117
>     118     logging.info('File {} downloaded.'.format(path))
> 
> ~/.conda/envs/env/lib/python3.8/site-packages/torchtext/_download_hooks.py in get_local_path(self, url, destination)
>      48             response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'}, stream=True)
>      49         else:
> ---> 50             response, filename = _get_response_from_google_drive(url)
>      51
>      52         with open(destination, 'wb') as f:
> 
> ~/.conda/envs/env/lib/python3.8/site-packages/torchtext/_download_hooks.py in _get_response_from_google_drive(url)
>      27                 ))
>      28         else:
> ---> 29             raise RuntimeError("Internal error: confirm_token was not found in Google drive link.")
>      30
>      31     url = url + "&confirm=" + confirm_token
> 
> RuntimeError: Internal error: confirm_token was not found in Google drive link.

**Comment by Nayef211** [comment] 2022-04-09 22:25
This is a duplicate of https://github.com/pytorch/text/issues/1638. Updating to torchtext version `0.12.0` should resolve the issue

**Closed by Nayef211** 2022-04-09 22:25 UTC
