### ISSUE TITLE
IWSLT2017 Download Issue in torchtext v0.11.0

### ISSUE THREAD

**Issue by A-Pandey20** [pytorch/text#1620] opened 2022-02-18 09:37 UTC
Downloaling IWSLT2017 raises Internal Error. This is the error message:
```python
RuntimeError: Internal error: confirm_token was not found in Google drive link.
```
I tried to use both the function and module version, but both raise the same error:
```python
train_iter, valid_iter, test_iter = torchtext.datasets.IWSLT2017()
```
```python
train_iter, valid_iter, test_iter = torchtext.datasets.iwslt2017.IWSLT2017()
```

Please have a look and fix it as soon as possible.

**Comment by erip** [comment] 2022-02-18 23:19
Duplicate of #1359.

**Comment by A-Pandey20** [comment] 2022-02-21 14:36
Yes, same with me. Neither one of the IWSLTs are working. Even for me they worked in the last week. Must be some cloud issue where the data is stored.

**Comment by erip** [comment] 2022-02-21 14:40
I think it is basically the torchtext code is somewhat flimsy wrt expected responses from gdrive. There's a good chance you're getting throttled by upstream and this is being misreported. We've recently migrated away from homegrown code for GDrive handling to the more robust torchdata approach, but that doesn't help for users stuck on 0.11.x...

**Comment by A-Pandey20** [comment] 2022-02-21 15:12
Ohh yes, makes sense. This might be the actual problem..

**Comment by austinvhuang** [comment] 2022-02-27 21:40
@erip any idea if the throttling is happening across all downloads or somehow specific to a client? IWSLT2016 data loading hasn't worked for the last two weeks for me now - wondering if gdrive has just cut off access from paperspace hosts at this point.

Any resolution suggestions? Should we be using the master branch instead of the 0.11.2 release?

**Comment by erip** [comment] 2022-02-27 21:42
@austinvhuang I suspect it's IP based, but that is a total guess. You could definitely try the main branch, but that's not going to change gdrive server responses, just what your client reports for diagnostics.

**Comment by austinvhuang** [comment] 2022-03-12 16:22
@erip I seem to be able to download datasets manually following the URL links in here https://github.com/pytorch/text/blob/c31a400990513d180fdbd4ae5d597781b6b7063a/test/asset/raw_datasets.jsonl so it seems like this is not necessarily google drive throttling downloads by IP but only a lack of this confirm_token response.

I'm not sure what confirm_token is for, but could it just be ignored as @parmeet suggests here?https://github.com/pytorch/text/issues/1359

**Comment by Nayef211** [comment] 2022-03-22 01:05
@austinvhuang were you able to verify if updating to version `0.12.0` resolved your issue?

**Comment by austinvhuang** [comment] 2022-04-02 06:25
@Nayef211 yes looks like it's resolved now, thanks.

**Closed** 2022-04-02 19:20 UTC
