### ISSUE TITLE
BucketIterator small batch in the middle

### ISSUE THREAD

**Issue by kiran-kate** [pytorch/text#640] opened 2019-11-13 20:13 UTC
I am using BucketIterator in the following code:
```
        self.dataset = TabularDataset(path=X, format='tsv',
                fields=self.fields)

        self.iter = BucketIterator(self.dataset, batch_size=self.batch_size,
                        sort_key=lambda x: len(x.text), sort_within_batch=True,
                        device=torch.device("cuda" if torch.cuda.is_available() else "cpu"))

        batch_data = {}
        batch_index = 0
        for batch in iter(self.iter):
            batch_X = batch.text.permute(1,0)
            batch_y = batch.labels
            print(len(batch_y))
            batch_data[batch_index] = batch_X, batch_y
            batch_index +=1
```

And the output of print(len(batch_y)) shows that a batch in the middle is the small batch and all other batches are of size batch_size. One would expect the last batch to be small. Issue #438 seems to report the same observation. This is affecting my downstream code, is there a way to avoid this behavior?

**Comment by abhinavarora** [comment] 2022-01-25 04:05
Closing issue as we have gotten rid of iterators and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:05 UTC

**Comment by abhinavarora** [comment] 2022-01-25 04:08
Closing issue as we have gotten rid of iterators and the issue is no more relevant. 
#1537
