### ISSUE TITLE
The provided example with TabularDataset and json is not working

### ISSUE THREAD

**Issue by hadifar** [pytorch/text#871] opened 2020-07-07 10:06 UTC
The example in Part 2, in this [page](https://pytorch.org/text/examples.html),  loading a JSON dataset, is not working and throws exception: 

```
Traceback (most recent call last):
    obj = json.loads(data)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 12)
```

My sample.json:

```
{
    "foods": {
    "fruits": ["Apple", "Banana"],
    "vegetables": [{"name": "lettuce"}, {"name": "marrow"}]
    }
}
```

Reproduce:

```
from torchtext import data
fields = {'foods.vegetables.name': ('vegetables', data.Field())}
dataset = data.TabularDataset(path='sample.json', format='json', fields=fields)
print(dataset.examples[0].vegetables)
```

Torch version: '1.5.1'
Torchtext version: '0.6.0'

**Comment by abhinavarora** [comment] 2022-01-25 05:10
Closing issue as we have gotten rid of `TabularDataset` and the issue is no more relevant.
#1537

**Closed by abhinavarora** 2022-01-25 05:10 UTC
Labels: obsolete
