### ISSUE TITLE
AttributeError: 'MultiLabelField' object has no attribute 'is_target'

### ISSUE THREAD

**Issue by akhilchitreddy** [pytorch/text#604] opened 2019-09-23 05:16 UTC
<ipython-input-5-8d5762e54eba> in train(self, run_order, epochs, no_print)
    721             field = RawField()
    722             field.is_target = False
--> 723             for iter, data in enumerate(self.train_iter):
    724                 self.classifier.zero_grad()
    725                 (x, x_lengths), y = data.Text, data.Description

/home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/torchtext/data/iterator.pyc in __iter__(self)
    154                     else:
    155                         minibatch.sort(key=self.sort_key, reverse=True)
--> 156                 yield Batch(minibatch, self.dataset, self.device)
    157             if not self.repeat:
    158                 return

/home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/torchtext/data/batch.pyc in __init__(self, data, dataset, device)
     25             self.fields = dataset.fields.keys()  # copy field names
     26             self.input_fields = [k for k, v in dataset.fields.items() if
---> 27                                  v is not None and not v.is_target]
     28             self.target_fields = [k for k, v in dataset.fields.items() if
     29                                   v is not None and v.is_target]

AttributeError: 'MultiLabelField' object has no attribute 'is_target'

**Comment by mttk** [comment] 2019-09-23 11:39
Is `MultiLabelField` your custom class, and does it inherit from `RawField` (it should)?
Also, could you paste the class in that case?

**Comment by abhinavarora** [comment] 2022-01-25 04:10
Closing issue as we have gotten rid of `MultilabelField` and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:10 UTC
