### ISSUE TITLE
Installing nightly TorchText with PyTorch forces CPU-only install

### ISSUE THREAD

**Issue by ebsmothers** [pytorch/text#1539] opened 2022-01-27 01:59 UTC
## 🐛 Bug
**Describe the bug**
When trying to install the nightly builds of PyTorch and TorchText with CUDA, the PyTorch install is coerced into a CPU-only one. 

Running `conda install pytorch torchtext cudatoolkit=11.3 -c pytorch-nightly` will try to install `pytorch==pytorch-nightly/linux-64::pytorch-1.11.0.dev20220126-py3.9_cpu_0`.

**To Reproduce**
Create a new conda environment, then try to install PyTorch and TorchText nightly builds with CUDA support.

```
conda create --name torchtext
conda activate torchtext
conda install pytorch torchtext cudatoolkit=11.3 -c pytorch-nightly
```

**Expected behavior**
Expected behavior should match the equivalent install process for e.g. TorchVision.
```
conda create --name torchvision
conda activate torchvision
conda install pytorch torchvision cudatoolkit=11.3 -c pytorch-nightly
```
This will try to install `pytorch==pytorch-nightly/linux-64::pytorch-1.11.0.dev20220126-py3.9_cuda11.3_cudnn8.2.0_0`, as expected (see also the below screenshots).

**Screenshots**

List of packages to be installed by `conda install pytorch torchtext -c pytorch-nightly`:

![Screen Shot 2022-01-26 at 5 46 14 PM](https://user-images.githubusercontent.com/24319399/151277809-21515e22-e5a0-49b5-8757-ded02e547709.jpg)

List of packages to be installed by `conda install pytorch torchtext -c pytorch-nightly`:
![Screen Shot 2022-01-26 at 5 47 17 PM](https://user-images.githubusercontent.com/24319399/151277823-edab52d6-1f8f-4818-8574-e9f1d6b5b09e.jpg)

**Environment**

Results of environment collection script:

```
python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.29

Python version: 2.7.18 (default, Mar  8 2021, 13:02:45)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-81-generic-x86_64-with-Ubuntu-20.04-focal
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] # packages in environment at /private/home/ebs/miniconda/envs/torchtext:
```

**Comment by parmeet** [comment] 2022-01-27 04:26
cc: @seemethere, @malfet

**Comment by malfet** [comment] 2022-02-16 00:01
Yeah, this is caused by https://github.com/pytorch/text/pull/1520

**Comment by atalman** [comment] 2022-02-18 00:03
Fixed by reverting the above comment:
Ref PR https://github.com/pytorch/text/pull/1619
Ref PR release branch: https://github.com/pytorch/text/pull/1618

**Closed by atalman** 2022-02-18 00:03 UTC
