### ISSUE TITLE
Numericalize torch.FloatTensor and torch.DoubleTensor

### ISSUE THREAD

**Issue by shafiul** [pytorch/text#535] opened 2019-05-10 18:12 UTC
Hi,

I was unable to use floating-point labels using the following field declaration:

    LABEL = data.Field(sequential=False, use_vocab=False, is_target=True, dtype=torch.DoubleTensor)

Got this error: "Specified Field dtype <class 'torch.DoubleTensor'> can not be used with use_vocab=False because we do not know how to numericalize it"

Would it be straight-forward to numericalize such fields?

Thanks!

**Comment by mttk** [comment] 2019-05-14 12:56
Hi, instead of using a concrete class for the `dtype` argument, you should use torch dtypes, ex:
`LABEL = data.Field(sequential=False, use_vocab=False, is_target=True, dtype=torch.float64)`

**Comment by zhangguanheng66** [comment] 2019-05-29 23:37
@shafiul if the issue is resolved, please feel free to close the issue. Thanks.

**Closed** 2019-05-30 09:38 UTC

**Comment by shafiul** [comment] 2019-06-01 15:52
Hi, sorry for the late response. Thank you for the feedback.
