### ISSUE TITLE
NestedField why not be another NestedField?

### ISSUE THREAD

**Issue by yyHaker** [pytorch/text#526] opened 2019-04-08 02:35 UTC
##### use torchText to load a list of list data
from torchtext import data
import pprint
pp = pprint.PrettyPrinter(indent=4)
char_filed = data.Field(sequential=True, use_vocab=True, tokenize=list)
word_field = data.NestedField(char_filed, use_vocab=True, tokenize=lambda x: x)
paras_field = data.NestedField(word_field, use_vocab=False, tokenize=lambda x: x)
mini_batch = [
    [["I", "love", "she"], ["she", "likes"]],
     [["me", "hate", "oh"], ["what", "whose"], ["so"]],
    [["me", "hate", "tes"], ["what", "is"], ["my"], ["lady"]],
]
padded = paras_field.pad(mini_batch)
pp.pprint(padded)
![image](https://user-images.githubusercontent.com/18585628/55695159-d9552a00-59e9-11e9-802c-a7e206da4bc9.png)
If TorchText support this, it would be load more complicated data like the example above.

**Comment by abhinavarora** [comment] 2022-01-25 04:12
Closing issue as we have gotten rid of `NestedField` and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:12 UTC
Labels: obsolete
