### ISSUE TITLE
torchtext.data.batch() generates empty batches when batch_size_fn is used

### ISSUE THREAD

**Issue by noreentry** [pytorch/text#816] opened 2020-06-08 11:51 UTC
## 🐛 Bug
First batch is empty when **batch_size_fn**(...) returns new effective batch size **greater** then **batch_size** specified:

``` python
list(torchtext.data.batch([1, 2, 3, 4, 5], batch_size=1, batch_size_fn=lambda new_, cnt_, bs_: 2)) == [[], 1, 2, 3, 4, 5]
```
expected `[1, 2, 3, 4, 5]`

`torchtext.__version__: 0.6.0`

**Comment by abhinavarora** [comment] 2022-01-25 05:11
Closing issue as we have gotten rid of `torchtext.data.batch` and the issue is no more relevant.
#1537

**Closed by abhinavarora** 2022-01-25 05:11 UTC
Labels: legacy
