### ISSUE TITLE
How to build the vocabulary of a field among two datasets

### ISSUE THREAD

**Issue by Life-0-1** [pytorch/text#347] opened 2018-07-04 14:22 UTC
I have two text files of training data, and the two corresponding Datasets are built based on the same field, how can I build its vocabulary among these two Datasets?

**Comment by domaala** [comment] 2018-07-30 12:24
@Life-0-1 If I am not mistaken:

`
FIELD.build_vocab(dataset_1, dataset_2)
`

This is commonly used when you want to build vocabulary out of train and validation sets together.

**Comment by kklemon** [comment] 2018-09-27 19:38
Why can't you just apply @domaala trick after you did the training? What use case do you specifically?

**Comment by zhangguanheng66** [comment] 2019-05-30 21:24
@domaala @kklemon Thanks for the help. If the issue is resolved, I will just close it.

**Closed by zhangguanheng66** 2019-05-30 21:24 UTC
