### ISSUE TITLE
TabularDataset fails if lines start with "

### ISSUE THREAD

**Issue by neychev** [pytorch/text#612] opened 2019-10-06 20:47 UTC
## 🐛 Bug
**Describe the bug**
`torchtext.data.TabularDataset` generates corrupted dataset from TSV file if one of the lines starts with quotation mark `"` 

**Example script to reproduce the bug is attached below**.

**To Reproduce**
1. Create file with one of the lines starting with `"` mark.
2. Create `TabularDataset` from this file.

**Expected behavior**
Dataset is generated correctly.

**Environment**

 - PyTorch Version: 1.2
 - OS: MacOS and Linux Ubuntu 18.04
 - How you installed PyTorch: pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.7 and 3.7.3 respectively
 - CUDA/cuDNN version: None and CUDA 10.1 respectively
 - GPU models and configuration: None
 - Any other relevant information: torchtext version 0.4.0

**Example code to reproduce**:
```
#!/usr/bin/env python
# coding: utf-8

# In[1]:
import torchtext
from torchtext.datasets import TranslationDataset
from torchtext.data import Field, BucketIterator

from nltk.tokenize import WordPunctTokenizer

# In[2]:
broken_lines = [
    'First\tfirst\n',
    '"Second\tsecond\n',
    'Third "sentence"\tthird\n',
    'Fourth\tfourth\n',
    'Fifth\tfifth\n',
    'Sixth\tsixth\n'
]

broken_lines_another_location = [
    'First\tfirst\n',
    '"Second\tsecond\n',
    'Third\tthird\n',
    'Fourth\tfourth\n',
    'Fifth"sentence"\tfifth\n',
    'Sixth\tsixth\n'
]

fixed_lines = [
    'First\tfirst\n',
    'Second\tsecond\n',
    'Third "sentence"\tthird\n',
    'Fourth\tfourth\n',
    'Fifth\tfifth\n',
    'Sixth\tsixth\n'
]

with open('broken_lines.txt', 'w') as iofile:
    iofile.writelines(broken_lines)
with open('broken_lines_another_location.txt', 'w') as iofile:
    iofile.writelines(broken_lines_another_location)
with open('fixed_lines.txt', 'w') as iofile:
    iofile.writelines(fixed_lines)

# In[3]:
tokenizer_W = WordPunctTokenizer()
def tokenize(x, tokenizer=tokenizer_W):
    return tokenizer.tokenize(x.lower())

# In[4]:
SRC = Field(tokenize=tokenize,
            init_token = '<sos>', 
            eos_token = '<eos>', 
            lower = True)

TRG = Field(tokenize=tokenize,
            init_token = '<sos>', 
            eos_token = '<eos>', 
            lower = True)

# In[5]:
dataset_broken = torchtext.data.TabularDataset(
    path='broken_lines.txt',
    format='tsv',
    fields=[('trg', TRG), ('src', SRC)]
)
print('Dataset generated from file where second line starts with " and next line with " is 4th length: {}'.format(len(dataset_broken)))
# Dataset generated from file where second line starts with " and next line with " is 4th length: 5

# In[6]:
dataset_broken_another_location = torchtext.data.TabularDataset(
    path='broken_lines_another_location.txt',
    format='tsv',
    fields=[('trg', TRG), ('src', SRC)]
)
print('Dataset generated from file where second line starts with " and next line with " is 3th length: {}'.format(len(dataset_broken_another_location)))
# Dataset generated from file where second line starts with " and next line with " is 3th length: 3

# In[7]:
print(vars(dataset_broken_another_location.examples[1]))
# {'trg': ['second', 'second', 'third', 'third', 'fourth', 'fourth', 'fifthsentence', '"'], 'src': ['fifth']}

# In[8]:
dataset_fixed = torchtext.data.TabularDataset(
    path='fixed_lines.txt',
    format='tsv',
    fields=[('trg', TRG), ('src', SRC)]
)
print('Dataset without lines starting with " length: {}'.format(len(dataset_fixed)))
# Dataset without lines starting with " length: 6

# In[9]:
with open('broken_lines.txt', 'r') as iofile:
    lines = iofile.readlines()
print('TSV file number of lines: {}'.format(len(lines)))
# TSV file number of lines: 6

```

**Comment by hawkeoni** [comment] 2019-10-10 13:33
Hello, @neychev!
It seems that the problem is a bit bigger than torchtext. It seems as even `pandas` can't correctly parse this data, because of a parameter called `quotechar` and `quoting`.

For example the following code
```python
pd.read_csv('broken_lines.txt', sep='\t', header=None)
```
produces a pandas.DataFrame similiar to TabularDataset. One way to negate it is to set an additional parameter 
```python
pd.read_csv('broken_lines.txt', sep='\t', header=None, quoting=3)
```
This way the DataFrame looks as it was intended to look. Tabular dataset has an additional argument csv_reader_params, which name is pretty self explanatory.
If you create TabularDataset with the following constructor
```python
dataset_broken = torchtext.data.TabularDataset(
    path='broken_lines.txt',
    format='tsv',
    fields=[('trg', TRG), ('src', SRC)], csv_reader_params={"quoting": 3}
)
```
everything should work as intended.
Hope this helps!

**Comment by hawkeoni** [comment] 2019-10-10 14:08
@zhangguanheng66 
The csv quoting mechanic is used to ignore delimiters, I can submit a PR to set it as csv.QUOTE_NONNUMERIC by default, because it seems best in torchtext.

**Comment by abhinavarora** [comment] 2022-01-25 04:09
Closing issue as we have gotten rid of `TabularDataset` and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:09 UTC
