### ISSUE TITLE
torchtext data Field should retrain with train_data when predict?

### ISSUE THREAD

**Issue by QDxiaoye** [pytorch/text#537] opened 2019-05-18 09:51 UTC
When I predict by model,  I find I have to retrain torchtext.data.Field object, Then i save the Field object by dill and the object file is big.  I want to know if I have another way to select.

**Comment by abhinavarora** [comment] 2022-01-25 04:11
Closing issue as we have gotten rid of Fields and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:11 UTC
