### ISSUE TITLE
Add official TorchText logo to documentation/README

### ISSUE THREAD

**Issue by Nayef211** [pytorch/text#2049] opened 2023-02-06 00:40 UTC
## 🚀 Feature

Now that TorchText has an official logo, we should add it to all of our documentation and README files. We can follow a process similar to TorchAudio (https://github.com/pytorch/audio/pull/2802).

**Comment by rshraga** [comment] 2023-02-07 20:48
this is a duplicate of https://github.com/pytorch/text/issues/2032

**Closed by rshraga** 2023-02-07 20:48 UTC
