### ISSUE TITLE
Multiple Fields on LanguageModeling Dataset

### ISSUE THREAD

**Issue by akurniawan** [pytorch/text#444] opened 2018-10-10 23:44 UTC
Currently we only accept single field on `LanguageModellingDataset` constructor
https://github.com/pytorch/text/blob/499e327ea53bdf67c648f5747ed26764283b968a/torchtext/datasets/language_modeling.py#L8

That assume people will only use word embedding to parse the dataset. To throw one example, according to this paper https://www.aaai.org/ocs/index.php/AAAI/AAAI16/paper/download/12489/12017, it is possible to instead of using words to predict words, we can use composed-chars (using cnn) to predict words. We can enable that by using two different fields, both for character and word level representation, it is hard to enable that with current `LanguageModellingDataset`. Now I am using my own code to replicate `LanguageModellingDataset` with extra fields and logic to run enable that, below is the snippet

```
class LanguageModelingDataset(data.Dataset):
    """Defines a dataset for language modeling."""

    def __init__(self, path, fields, newline_eos=True,
                 encoding='utf-8', **kwargs):
        """Create a LanguageModelingDataset given a path and a field.
        Arguments:
            path: Path to the data file.
            fields: Dictionary containing keyword 
            newline_eos: Whether to add an <eos> token for every newline in the
                data file. Default: True.
            Remaining keyword arguments: Passed to the constructor of
                data.Dataset.
        """
        if isinstance(fields, dict):
            raise ValueError("`fields` must be an instance of dictionary!")
        if "text" not in fields.keys():
            raise AttributeError("Field with key `text` is required to preprocess the data!")
        text_field = fields["text"]
        text = []
        with io.open(path, encoding=encoding) as f:
            for line in f:
                text += text_field.preprocess(line)
                if newline_eos:
                    text.append(u'<eos>')

        tuple_fields = [(k, v) for k, v in fields.items()]
        examples = [data.Example.fromlist([text], tuple_fields)]
        super(LanguageModelingDataset, self).__init__(
            examples, fields, **kwargs)
```

Where `fields` contains both word and character representation field.
Not sure if this the best design, and not sure if this worth the PR. But, let me know if you have any thought!

**Comment by bentrevett** [comment] 2018-10-11 14:44
Could you give an example of how to use this? The following only gives me the `text` field:

```python
TEXT = Field()
CHARS = Field(tokenize=list)

fields = {'text': TEXT, 'chars': CHARS}

train_data = LanguageModelingDataset('example.txt', fields)
```

I had to change `if isinstance(fields, dict)` to `if not isinstance(fields,dict)` which correctly matches up with the `ValueError` message, but that might have also caused my problems.

**Comment by akurniawan** [comment] 2018-10-11 23:37
@bentrevett sorry, I think I put the wrong code. This should be the right one
```
class LanguageModelingDataset(data.Dataset):
    """Defines a dataset for language modeling."""

    def __init__(self,
                 path,
                 fields,
                 newline_eos=True,
                 encoding='utf-8',
                 **kwargs):
        """Create a LanguageModelingDataset given a path and a field.
        Arguments:
            path: Path to the data file.
            fields: Dictionary containing keyword
            newline_eos: Whether to add an <eos> token for every newline in the
                data file. Default: True.
            Remaining keyword arguments: Passed to the constructor of
                data.Dataset.
        """
        if not isinstance(fields, dict):
            raise ValueError("`fields` must be an instance of dictionary!")
        if "text" not in fields.keys():
            raise AttributeError(
                "Field with key `text` is required to preprocess the data!")

        text_field = fields["text"]
        text = []
        with io.open(path, encoding=encoding) as f:
            for line in f:
                text += text_field.preprocess(line)
                if newline_eos:
                    text.append(u'<eos>')

        tuple_fields = [tuple(zip(*fields.items()))]
        examples = [data.Example.fromlist([text], tuple_fields)]
        super(LanguageModelingDataset, self).__init__(examples, fields,
                                                      **kwargs)
```

and we may need to create a new `BPTTIterator`, since for now the `BPTTIterator` still hardcoding the fields `TEXT` and `TARGET`

**Comment by yangyaofei** [comment] 2019-05-29 12:02
```
class BPTTIterator(torchtext.data.BPTTIterator):
    """custom iterator for hybrid char-word"""

    def __iter__(self):
        text = self.dataset[0].text
        # char = self.dataset[0].char
        TEXT = self.dataset.fields['text']
        # CHAR = self.dataset.fields['char']
        TEXT.eos_token = None
        # CHAR.eos_token = None
        text = text + ([TEXT.pad_token] * int(math.ceil(len(text) / self.batch_size)
                                              * self.batch_size - len(text)))
        data = TEXT.pad([text])
        data = TEXT.numericalize(
            data, device=self.device)
        size = list(data.size())
        size[0] = self.batch_size
        size[1] = -1
        data = data.view(*size).transpose(0, 1).contiguous()
        dataset = Dataset(examples=self.dataset.examples, fields=[
            ('text', TEXT), ('target', TEXT)])
        while True:
            for i in range(0, len(self) * self.bptt_len, self.bptt_len):
                self.iterations += 1
                seq_len = min(self.bptt_len, len(data) - i - 1)
                batch_text = data[i:i + seq_len]
                batch_target = data[i + 1:i + 1 + seq_len]
                if TEXT.batch_first:
                    batch_text = batch_text.transpose(0, 1).contiguous()
                    batch_target = batch_target.transpose(0, 1).contiguous()
                yield Batch.fromvars(
                    dataset, self.batch_size,
                    text=batch_text,
                    target=batch_target)
            if not self.repeat:
                return


def gen_bptt_iter(dataset, batch_size, bptt_len, device):
    for batch_word, batch_char in zip(
            BPTTIterator(dataset[0], batch_size, bptt_len, device=device),
            BPTTIterator(dataset[1], batch_size, bptt_len, device=device),
    ):
        yield batch_word.text, batch_char.text, batch_word.target, batch_char.target


def gen_language_model_corpus(dataset_cls: torchtext.datasets.LanguageModelingDataset):
    field_char = NestedField(Field(
        pad_token=PAD_WORD,
        tokenize=list,
        init_token=SOS_WORD,
        eos_token=EOS_WORD,
        batch_first=True),
        pad_token=PAD_WORD
    )
    field_word = Field(batch_first=True)
    dataset_char = dataset_cls.splits(field_char)
    dataset_word = dataset_cls.splits(field_word)
    field_char.build_vocab(dataset_char[0])
    field_word.build_vocab(dataset_word[0])
    return [_ for _ in zip(dataset_word, dataset_char)], field_word, field_char
```

I use this to get a both char and word

**Comment by zhangguanheng66** [comment] 2019-05-30 20:07
@yangyaofei @akurniawan if a possible PR can help resolve the issue, please feel free to submit one with proper unit tests and docs. Thanks.

**Comment by satya77** [comment] 2020-05-29 09:56
I used the comments in this post to make batcher for character and word level models, you can find it here: https://github.com/satya77/torchtext_extension

**Comment by abhinavarora** [comment] 2022-01-25 04:06
Closing issue as we have gotten rid of`LanguageModelingDataset` and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:06 UTC
Labels: enhancement
