### ISSUE TITLE
How to use NestedField?

### ISSUE THREAD

**Issue by cswangjiawei** [pytorch/text#368] opened 2018-08-24 08:41 UTC
What is the role of NestedField, the documentation says it is used to implement character embeddings, but I don't understand it. And how to use NestedField?

**Comment by kklemon** [comment] 2018-09-27 19:31
The documentatin for NestedField is indeed a bit sparse. From my understanding the intention is to inherit attributes like the vocabular or tokenizer between different fields. Basically like normal inheritance for classes, but just specifically for fields. For example you might have a base Field that does tokenization and then different nested fields that inherit the tokenizer from the base field but apply different kind of pre-processing.

You might consider the `test/data/test_field.py` file for actual code examples. For me, line [496](https://github.com/pytorch/text/blob/master/test/data/test_field.py#L494) made it clear what the purpose is and how it actually works.

**Comment by abhinavarora** [comment] 2022-01-25 04:00
Closing issue as we have gotten rid of`NestedField` and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:00 UTC
Labels: docs
