### ISSUE TITLE
Behavior of Iterator regards sorting is confusing

### ISSUE THREAD

**Issue by kklemon** [pytorch/text#440] opened 2018-10-07 18:12 UTC
I noticed that the behavior of Iterators.splits() is a bit confusing regarding how and if it applies sorting to the passed datasets. In particular when you pass different datasets to Iterator.splits() without providing a specific sort key either to the dataset or to the splits() method, sorting will be enabled for all returned iterators except the first one, the one for training respectively. This resulted in a very confusing error at first what even caused me to study the corresponding code.

Consider the following example code which causes the error at the last line:
```python
text_field = Field()
label_field = Field(sequential=False)

fields = [
    ('text', text_field),
    ('label', label_field)
]

# build some sample dataset
examples = list(map(lambda x: Example.fromlist((str(x), x), fields), range(10)))
dataset = Dataset(examples, fields)
train, val = dataset.split()

text_field.build_vocab(dataset)
label_field.build_vocab(dataset)

train_it, val_it = Iterator.splits([train, val], batch_size=32)

# works
list(train_it)

# error
list(val_it)
```

Now this behavior even seems logical to me in the end but still I think that it is a bit confusing and not well documented. But after rethinking it again, maybe it even could be seen as a bug for some specific cases.

Consider that you have a Dataset entirely made of non-sequential and/or categorical data. This is probably unusual for an nlp dataset but possible. Now for such a dataset you would not expect to be sortable at all but still Iterator.splits()* would assume it and try to apply sorting to all datasets but the first one.

My propose would be, that the constructor of Iterator does not set `self.sort` only depending on the value of the train and sort argument but also if a sort key is given at all.

For example the logic of setting `self.sort` could be changed according to the following snipped assuming that it is executed after the value of `self.sort_key` is determined.
```python
if sort:
    if self.sort_key is None:
        raise Exception('sort_key argument must be passed if sorting should be applied')
    self.sort = True
else:
    self.sort = not train and self.sort_key
```

\* This of course also applies to a normally instantiated Iterator when the train argument is set to False but no sort_key is given.

**Comment by zhangguanheng66** [comment] 2019-05-30 20:10
@kklemon would like to submit a PR with proper docs for this issue. Thanks.

**Comment by abhinavarora** [comment] 2022-01-25 04:05
Closing issue as we have gotten rid of iterators and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:05 UTC
Labels: question, docs
