### ISSUE TITLE
Would you please include sort_idex in the modules in Iterator ?

### ISSUE THREAD

**Issue by moomooda** [pytorch/text#631] opened 2019-10-29 02:12 UTC
## 🚀 Feature

**Motivation**

I want to get the original index of the sorted lists of the batch, because getting the sorted lists into original index after the training process of model is helpful

**Comment by abhinavarora** [comment] 2022-01-25 04:09
Closing issue as we have gotten rid of iterators and the issue is no more relevant. 
#1537

**Closed by abhinavarora** 2022-01-25 04:09 UTC
Labels: feature request, obsolete
