### ISSUE TITLE
BucketIterator iterating more than the length

### ISSUE THREAD

**Issue by ksurya** [pytorch/text#406] opened 2018-09-24 01:30 UTC
I have code like this:

```python
batch_size = 100

train_dataset, test_dataset = convos.split(split_ratio=0.7)

train_iterator = torchtext.data.BucketIterator(
    train_dataset,
    batch_size=3000,
    sort_key=lambda x: torchtext.data.interleave_keys(len(x.context), len(x.response)),
    device=device
)

print("Batch size: ", batch_size)
print("Train size: ", len(train_iterator))
```
```text
Batch size:  100
Train size:  1
```

Following this, I do

```python
for count, batch in enumerate(train_iterator):
    print(count)
```

And this program doesn't stop (at least I checked until count = 3000). I suppose it should iterate just once!

**Comment by nzw0301** [comment] 2018-09-24 14:15
Yes, your code does not stop. 

`Iteration` class's behavior may be confusing. If you want to iterate just once, you need to pass `False` to `repeat` argument like this.

```python
torchtext.data.BucketIterator(
    train_dataset,
    batch_size=3000,
    sort_key=lambda x: torchtext.data.interleave_keys(len(x.context), len(x.response)),
    device=device,
    repeat=False
)
```

`False` as the default value of `repeat` seems to be better than `None`.

**Comment by ksurya** [comment] 2018-09-24 14:18
Does this mean, the iterator keeps repeating and is there a way to fix the number of repeats?

**Comment by nzw0301** [comment] 2018-09-24 14:40
Yes, if you want to iterate just once in each epoch, my code snippet above can do that.

**Comment by ksurya** [comment] 2018-09-25 20:00
Thanks you.  I would suggest to set  default `repeat` to `True` in `BucketIterator` -- that may break existing codebases but I think typically iterators are not in infinite loop.

**Comment by mttk** [comment] 2018-09-25 20:51
Yeah, I believe it is more or less agreed that the default infinite loop in Iterators is confusing.

I'd say that the expected behavior is to iterate for one epoch (so, the default would be `repeat=False`), and leave the infinite loop as an option if users prefer it. This might break something backwards but it's manageable.

**Comment by zhangguanheng66** [comment] 2019-05-30 20:46
I will just close this issue since a PR is attached. Thanks all for the help.

**Closed by zhangguanheng66** 2019-05-30 20:46 UTC
