### ISSUE TITLE
NameError: name 'IterableWrapper' is not defined

### ISSUE THREAD

**Issue by rkingery** [pytorch/text#1744] opened 2022-05-26 11:17 UTC
## 🐛 Bug

Hello, I am trying to load torchtext datasets to reproduce a couple of the tutorials using the new PyTorch MPS support on Mac. After downloading torchdata I get the following error when trying to load any of the datasets in `torchtext.datasets`:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [51], in <cell line: 1>()
----> 1 data = torchtext.datasets.IMDB(
      2     '~/data',
      3     split='train'
      4 )

File ~/opt/anaconda3/envs/main/lib/python3.10/site-packages/torchtext/data/datasets_utils.py:193, in _create_dataset_directory.<locals>.decorator.<locals>.wrapper(root, *args, **kwargs)
    191 if not os.path.exists(new_root):
    192     os.makedirs(new_root, exist_ok=True)
--> 193 return fn(root=new_root, *args, **kwargs)

File ~/opt/anaconda3/envs/main/lib/python3.10/site-packages/torchtext/data/datasets_utils.py:155, in _wrap_split_argument_with_fn.<locals>.new_fn(root, split, **kwargs)
    153 result = []
    154 for item in _check_default_set(split, splits, fn.__name__):
--> 155     result.append(fn(root, item, **kwargs))
    156 return _wrap_datasets(tuple(result), split)

File ~/opt/anaconda3/envs/main/lib/python3.10/site-packages/torchtext/datasets/imdb.py:86, in IMDB(root, split)
     81 if not is_module_available("torchdata"):
     82     raise ModuleNotFoundError(
     83         "Package `torchdata` not found. Please install following instructions at `https://github.com/pytorch/data`"
     84     )
---> 86 url_dp = IterableWrapper([URL])
     88 cache_compressed_dp = url_dp.on_disk_cache(
     89     filepath_fn=partial(_filepath_fn, root),
     90     hash_dict={_filepath_fn(root): MD5},
     91     hash_type="md5",
     92 )
     93 cache_compressed_dp = HttpReader(cache_compressed_dp).end_caching(mode="wb", same_filepath_fn=True)

NameError: name 'IterableWrapper' is not defined
```

My environment screen dump is below. Thanks.

```
Collecting environment information...
PyTorch version: 1.13.0.dev20220525
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.13.0.dev20220525
[pip3] torchaudio==0.12.0.dev20220525
[pip3] torchdata==0.5.0.dev20220525
[pip3] torchtext==0.13.0.dev20220525
[pip3] torchvision==0.14.0.dev20220525
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220525          pypi_0    pypi
[conda] torchaudio                0.12.0.dev20220525          pypi_0    pypi
[conda] torchdata                 0.5.0.dev20220525          pypi_0    pypi
[conda] torchtext                 0.13.0.dev20220525          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220525          pypi_0    pypi

torchtext version is  0.13.0.dev20220525
```

**Comment by parmeet** [comment] 2022-05-26 14:45
hmm, seem strange. The exception is not raised [here](https://github.com/pytorch/text/blob/fe57328975817161b71b6c34a9f82ec8ddb88c31/torchtext/datasets/imdb.py#L81) which means that torchdata is already available on the system (as also listed in your environment). If that is the case, `Iterablewrapper` should have been imported [here](https://github.com/pytorch/text/blob/fe57328975817161b71b6c34a9f82ec8ddb88c31/torchtext/datasets/imdb.py#L11).

**Comment by tianyu-z** [comment] 2022-06-28 10:20
I have the same bug

**Comment by yushikmr** [comment] 2022-07-09 18:12
I have the same bug

my env:
```
python=3.8.5
torch==1.12.0
torchtext==0.13.0
```

**Comment by Nayef211** [comment] 2022-07-11 16:47
I also tried reproing but am not able to do so
```
>>> from torchtext.datasets import WikiText2
>>> train_iter = WikiText2(split='train')
```

Env:
```
python==3.10.0
pytorch==1.12.0
torchtext==0.13.0
torchdata==0.4.0
```


@ejguan would you happen to have any ideas as to what could cause this error to surface? As @parmeet mentioned, `torchdata` is already available on the system and `IterableWrapper` has been imported.

**Comment by ejguan** [comment] 2022-07-11 17:34
On MacOS, I can't reproduce it either
- nightly releases
```
torch=1.13.0.dev20220711
torchtext=0.14.0.dev20220707
torchdata=0.5.0.dev20220711
```
- official releases
```
torch=1.12.0
torchtext=0.13.0
torchdata=0.4.0
```

@rkingery Could you please try to use the latest nightly release?

@tianyu-z @yushikmr Could you please check if torchdata is installed with the right version.


> As @parmeet mentioned, `torchdata` is already available on the system and `IterableWrapper` has been imported.

TBH, I agree this is super strange and I can't reproduce it.

**Comment by Nayef211** [comment] 2022-07-20 17:19
@rkingery let me know if @MadSleep's suggestion helps fix your issue. Will close out this issue if it does.

**Comment by ejguan** [comment] 2022-07-21 13:37
@ivaquero 

You need torchdata==0.4.0 to work with pytorch 1.12.0

**Comment by yushikmr** [comment] 2022-07-21 13:50
I found same error in spite of  `torchdata==0.4.0 to work with pytorch 1.12.0`
#1819 
```
Python: 3.10.5

pytorch==1.12.0
torchdata==0.4.0
torchtext=0.13.0
```

**Comment by ivaquero** [comment] 2022-07-21 14:03
> @ivaquero 
> 
> 
> 
> You need torchdata==0.4.0 to work with pytorch 1.12.0

Unfortunately, there is no torchdata==0.4.0 osx-arm64 build on conda channels.

**Comment by ejguan** [comment] 2022-07-21 14:11
@ivaquero I see. I will see if torchdata can provide one for m1 mac.

**Comment by MadSleep** [comment] 2022-07-21 18:41
Try to run your code on google colab

**Comment by Pythonash** [comment] 2022-10-12 12:39
I found the solution in operating on colab.

You should rerun your notebook as below:

```
!pip install torchdata
exit()
```

and re-turn on your runtime and:

```
import torchtext
import torchdata
```

Then, your task will be working on well.

**Comment by ejguan** [comment] 2022-10-12 15:00
I am closing this Issue because TorchData currently provides pre-assembled binaries for Mac M1 on [PyPI](https://pypi.org/project/torchdata/#files) and [Conda](https://anaconda.org/pytorch/torchdata/files) after 0.4.1

You should be able to install `torchdata == 0.4.1` and `torchtext == 0.13.1` via
- `pip3 install torch torchdata torchtext`
- `conda install pytorch torchdata torchtext -c pytorch` 

So, this issue should be resolved for Mac M1.

**Closed by ejguan** 2022-10-12 15:00 UTC
