### ISSUE TITLE
test_field error typeError: process() missing 2 required positional arguments: 'device' and 'train'

### ISSUE THREAD

**Issue by VectorChanger0** [pytorch/text#485] opened 2018-12-12 08:59 UTC
```
import torch
import torchtext.data as data

raw_field = data.RawField()
field = data.Field(sequential=True, use_vocab=False, batch_first=True)

batch = [[1, 2, 3], [2, 3, 4]]
batch_tensor = torch.LongTensor(batch)

raw_field_processed = raw_field.process(batch)
field_processed = field.process(batch)

assert raw_field_processed == batch
assert field_processed.data.equal(batch_tensor)
```

**Traceback** (most recent call last):
  File "D:\anaconda\envs\me\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-78-21455d966ee5>", line 11, in <module>
    field_processed = field.process(batch)
**TypeError: process() missing 2 required positional arguments: 'device' and 'train'**
pycharm py3.6  pytorch 0.4.1 torchtext 0.2.3 windows 10

**Comment by JohanWork** [comment] 2019-02-15 11:52
Did you mange to solve it?

**Comment by sparkingdark** [comment] 2020-12-01 15:38
Is this still open or the issue is fixed @zhangguanheng66

**Comment by Nayef211** [comment] 2022-06-24 00:27
Closing this since `torchtext.data.Field` has been deleted and is no longer available in the latest releases of our library.

**Closed by Nayef211** 2022-06-24 00:27 UTC
